### ISSUE TITLE
Need more available currencies.

### ISSUE THREAD

**Issue by BloodShadow174** [WinoGarcia/CryptoPay#1]
In one of the updates CryptoBot, more fiat currencies were added.
Please add more assets to [CryptoPay.Types.Assets](https://github.com/WinoGarcia/CryptoPay/blob/main/CryptoPay/Types/Assets.cs).

New currencies:
- Belarusian ruble (BYN)
- Ukrainian hryvnia (UAH)
- Pound sterling (GBP)
- Renminbi (CNY)
- Kazakhstani tenge (KZT)
- Uzbekistani som (UZS)
- Georgian lari (GEL)
- Turkish lira (TRY)
- Armenian dram (AMD)
- Thai baht (THB)
- Indian rupee (INR)

**Comment by WinoGarcia** [comment]
Thanks.
I added last changes from CryptoBot. 
See [latest release](https://github.com/WinoGarcia/CryptoPay/releases/tag/release%2Fv1.1.3.1)
