### ISSUE TITLE
You may need to add a new asset

### ISSUE THREAD

**Issue by BloodShadow174** [WinoGarcia/CryptoPay#5]
[TRX support has been added to the test bot](https://t.me/CryptoBotTests/73), you may need to add a [new asset](https://github.com/WinoGarcia/CryptoPay/blob/main/CryptoPay/Types/Assets.cs) in the near future. Should a PR be opened?

**Comment by WinoGarcia** [comment]
Hi. 
I [added TRX](https://github.com/WinoGarcia/CryptoPay/releases/tag/release%2Fv1.1.3.5) (Tron) asset.
